import { expect, test } from '@playwright/test'
test('complete mobile workout, restore drafts, inspect technique and history, reuse actual results', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('./')
  await expect(page.getByRole('heading', { name: 'Домашняя тренировка.' })).toBeVisible()
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  await expect(page.locator('.exercise-card')).toHaveCount(14)
  const row = page.locator('.exercise-card').filter({ has: page.getByRole('heading', { name: 'Тяга двух гантелей к поясу', exact: true }) })
  await row.getByRole('textbox', { name: 'Вес, подход 1', exact: true }).fill('9,5')
  await row.getByRole('textbox', { name: 'Повторения, подход 1', exact: true }).fill('12')
  await row.getByRole('textbox', { name: 'Вес, подход 2', exact: true }).fill('7')
  await row.getByRole('button', { name: 'Подход 1 выполнен', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Продолжить тренировку' }).click()
  await expect(row.getByRole('textbox', { name: 'Вес, подход 1', exact: true })).toHaveValue('9.5')
  await expect(row.getByRole('button', { name: 'Подход 1 выполнен', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await row.locator('.exercise-open').click()
  await expect(page.locator('.focus-progress')).toContainText('16 / 29')
  await page.getByRole('button', { name: 'Техника упражнения', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  const illustration = page.getByRole('img', { name: 'Техника: Тяга двух гантелей к поясу' })
  await expect(illustration).toBeVisible()
  await expect.poll(() => illustration.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true)
  await expect(page.getByText('Локти идут назад, к поясу.')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Следующее упражнение', exact: true }).click()
  await expect(page.locator('.focus-title')).toContainText('Разгибание на трицепс из-за головы')
  await page.getByRole('button', { name: 'Все упражнения' }).click()
  await page.getByRole('checkbox', { name: 'Блок «Корпус + мобилити» выполнен' }).check()
  await page.getByRole('checkbox', { name: 'Блок «Растяжка» выполнен' }).check()
  const unfinished = page.locator('.set-check[aria-pressed="false"]')
  while (await unfinished.count()) await unfinished.first().click()
  await expect(page.locator('.workout-progress')).toContainText('20 из 20 подходов выполнено')
  await page.getByRole('button', { name: 'К завершению', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Тренировка завершена 💪' })).toBeVisible()
  await page.getByRole('button', { name: 'Завершить и сохранить' }).click()
  await expect(page.getByRole('button', { name: 'Начать тренировку' })).toBeVisible()
  await page.getByRole('button', { name: 'История тренировок', exact: true }).click()
  await expect(page.locator('.history-card')).toContainText('29 / 29 упражнений')
  await page.locator('.history-card').click()
  await expect(page.locator('.result-row').filter({ hasText: 'Тяга двух гантелей к поясу' })).toContainText('9.5 кг × 12')
  await page.getByRole('button', { name: 'На главную', exact: true }).click()
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  await expect(row.getByRole('textbox', { name: 'Вес, подход 1', exact: true })).toHaveValue('9.5')
  await expect(row.getByRole('textbox', { name: 'Вес, подход 2', exact: true })).toHaveValue('7')
  await expect(row.getByRole('textbox', { name: 'Повторения, подход 1', exact: true })).toHaveValue('12')
  await expect(row.getByRole('button', { name: 'Подход 1 выполнен', exact: true })).toHaveAttribute('aria-pressed', 'false')
  expect(errors).toEqual([])
})
test('PWA loads and persists a session offline, with installable manifest and icons', async ({ page, context }) => {
  await page.goto('./')
  await page.evaluate(async () => {
    await navigator.serviceWorker.ready
    if (!navigator.serviceWorker.controller) await new Promise<void>(resolve => navigator.serviceWorker.addEventListener('controllerchange', () => resolve(), { once: true }))
  })
  const manifest = await (await page.request.get('manifest.webmanifest')).json()
  expect(manifest.display).toBe('standalone')
  for (const icon of manifest.icons) expect((await page.request.get(icon.src)).status()).toBe(200)
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  await page.locator('.set-check').first().click()
  await context.setOffline(true)
  await page.reload()
  // Chromium can report navigator.onLine=true after a service-worker navigation.
  // Verify a real uncached network request fails while the cached application loads.
  expect(await page.evaluate(() => fetch('./uncached-offline-probe').then(() => false, () => true))).toBe(true)
  await expect(page.getByRole('button', { name: 'Продолжить тренировку' })).toBeVisible()
  await page.getByRole('button', { name: 'Продолжить тренировку' }).click()
  await expect(page.locator('.set-check').first()).toHaveAttribute('aria-pressed', 'true')
  await page.locator('.set-check').nth(1).click()
  await page.reload()
  await page.getByRole('button', { name: 'Продолжить тренировку' }).click()
  await expect(page.locator('.workout-progress')).toContainText('2 из 20 подходов выполнено')
})
test('partial sessions and storage errors remain explicit; mobile layout fits 320px', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await page.goto('./')
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.locator('.set-check').first().click()
  await page.getByRole('button', { name: 'Завершить тренировку', exact: true }).click()
  await expect(page.getByText('Невыполненные подходы сохранятся как пропущенные.')).toBeVisible()
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('quota') } })
  await page.getByRole('button', { name: 'Завершить и сохранить' }).click()
  await expect(page.getByRole('alert')).toContainText('Не удалось сохранить тренировку')
  await expect(page.getByRole('button', { name: 'Завершить и сохранить' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Продолжить тренировку' }).click()
  await page.getByRole('button', { name: 'Завершить тренировку', exact: true }).click()
  await page.getByRole('button', { name: 'Завершить и сохранить' }).click()
  await page.getByRole('button', { name: 'История тренировок', exact: true }).click()
  await expect(page.locator('.history-card')).toContainText('1 / 29 упражнений')
})

test('mobility uses one persistent block checkbox with technique and no numeric controls', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  const block = page.locator('.exercise-block').first()
  const checkbox = block.getByRole('checkbox', { name: 'Блок «Корпус + мобилити» выполнен' })
  await expect(block.locator('.mobility-row')).toHaveCount(10)
  await expect(block.getByRole('textbox')).toHaveCount(0)
  await expect(block.locator('.set-check')).toHaveCount(0)
  await expect(block).not.toContainText('План:')
  await block.getByRole('button', { name: 'Техника: Кошка-собака', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Кошка-собака')
  await page.getByRole('button', { name: 'Закрыть технику' }).click()
  await checkbox.check()
  await expect(page.locator('.workout-progress')).toContainText('10 / 29 упражнений')
  await expect(page.locator('.workout-progress')).toContainText('0 из 20 подходов выполнено')
  await page.reload()
  await page.getByRole('button', { name: 'Продолжить тренировку' }).click()
  await expect(checkbox).toBeChecked()
  await checkbox.uncheck()
  await expect(page.locator('.workout-progress')).toContainText('0 / 29 упражнений')
  await checkbox.check()
  await page.getByRole('button', { name: 'Завершить тренировку', exact: true }).click()
  await page.getByRole('button', { name: 'Завершить и сохранить' }).click()
  await page.getByRole('button', { name: 'История тренировок', exact: true }).click()
  await page.locator('.history-card').click()
  await expect(page.locator('.result-row').first()).toContainText('Блок выполнен')
  await expect(page.locator('.result-row').first()).not.toContainText('повт.')
  await page.getByRole('button', { name: 'На главную', exact: true }).click()
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  await expect(checkbox).not.toBeChecked()
})

test('stretching has one independent persistent checkbox and follows legs in focus mode', async ({ page }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  const block = page.locator('#block-4')
  const checkbox = block.getByRole('checkbox', { name: 'Блок «Растяжка» выполнен' })
  const mobility = page.getByRole('checkbox', { name: 'Блок «Корпус + мобилити» выполнен' })
  await expect(block.locator('.mobility-row')).toHaveCount(5)
  await expect(block.getByRole('checkbox')).toHaveCount(1)
  await expect(block.getByRole('textbox')).toHaveCount(0)
  await expect(block.locator('.set-check')).toHaveCount(0)
  await expect(block).not.toContainText('секунд')
  await block.getByRole('button', { name: 'Техника: Ягодичная «четвёрка»' }).click()
  await expect(page.getByRole('dialog')).toContainText('Ягодичная «четвёрка»')
  await page.getByRole('button', { name: 'Закрыть технику' }).click()
  await checkbox.check()
  await expect(mobility).not.toBeChecked()
  await expect(page.locator('.workout-progress')).toContainText('5 / 29 упражнений')
  await expect(page.locator('.workout-progress')).toContainText('0 из 20 подходов выполнено')
  await page.reload()
  await page.getByRole('button', { name: 'Продолжить тренировку' }).click()
  await expect(checkbox).toBeChecked()
  await checkbox.uncheck()
  await expect(page.locator('.workout-progress')).toContainText('0 / 29 упражнений')
  await page.locator('.exercise-card').filter({ has: page.getByRole('heading', { name: 'Круговые движения коленом', exact: true }) }).locator('.exercise-open').click()
  await page.getByRole('button', { name: 'К растяжке', exact: true }).click()
  await expect(checkbox).toBeVisible()
  await checkbox.check()
  await page.getByRole('button', { name: 'Завершить тренировку', exact: true }).click()
  await page.getByRole('button', { name: 'Завершить и сохранить' }).click()
  await page.getByRole('button', { name: 'История тренировок', exact: true }).click()
  await page.locator('.history-card').click()
  const result = page.locator('.result-row').filter({ has: page.getByRole('heading', { name: 'Растяжка', exact: true }) })
  await expect(result).toContainText('Блок выполнен')
  await expect(result).not.toContainText('сек')
  await page.getByRole('button', { name: 'На главную', exact: true }).click()
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  await expect(checkbox).not.toBeChecked()
})

test('clean home and copied result text from summary and saved history', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('./')
  await expect(page.getByText('Последняя тренировка', { exact: true })).toHaveCount(0)
  await expect(page.getByText('ОДНА ТРЕНИРОВКА. ВСЁ ТЕЛО.', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  await page.getByRole('checkbox', { name: 'Блок «Корпус + мобилити» выполнен' }).check()
  const row = page.locator('.exercise-card').filter({ has: page.getByRole('heading', { name: 'Тяга двух гантелей к поясу', exact: true }) })
  await row.getByRole('textbox', { name: 'Вес, подход 1', exact: true }).fill('9,5')
  await row.getByRole('textbox', { name: 'Повторения, подход 1', exact: true }).fill('12')
  await row.getByRole('button', { name: 'Подход 1 выполнен', exact: true }).click()
  await page.getByRole('button', { name: 'Завершить тренировку', exact: true }).click()
  await page.getByRole('button', { name: 'Скопировать результаты' }).click()
  await expect(page.getByRole('status')).toHaveText('Скопировано')
  const text = await page.evaluate(() => navigator.clipboard.readText())
  expect(text).toContain('Домашняя тренировка\n')
  expect(text).toContain('Корпус + мобилити\n✓ Блок выполнен')
  expect(text).toContain('Подход 1: 9,5 кг × 12 повт. · ✓ выполнен')
  expect(text).toContain('Подход 2: 8 кг × 15 повт. · — не выполнен')
  expect(text).toContain('Растяжка\n— Блок пропущен')
  await page.getByRole('button', { name: 'Завершить и сохранить' }).click()
  await page.getByRole('button', { name: 'История тренировок', exact: true }).click()
  await page.locator('.history-card').click()
  await page.getByRole('button', { name: 'Скопировать результаты' }).click()
  await expect(page.getByRole('status')).toHaveText('Скопировано')
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(text)
})
test('clipboard denial offers selectable text, without false success or losing the session', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 720 })
  await page.goto('./')
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  await page.locator('.set-check').first().click()
  await page.getByRole('button', { name: 'Завершить тренировку', exact: true }).click()
  await page.evaluate(() => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('Denied') } } }) })
  await page.getByRole('button', { name: 'Скопировать результаты' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Текст результатов тренировки' })).toHaveValue(/Домашняя тренировка/)
  await expect(page.getByRole('status')).not.toHaveText('Скопировано')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Выделить весь текст' }).click()
  const selection = await page.getByRole('textbox').evaluate((node: HTMLTextAreaElement) => node.selectionEnd - node.selectionStart)
  expect(selection).toBeGreaterThan(100)
  await page.getByRole('button', { name: 'Закрыть', exact: true }).click()
  await page.getByRole('button', { name: 'Вернуться к упражнениям' }).click()
  await expect(page.locator('.set-check').first()).toHaveAttribute('aria-pressed', 'true')
})

test('all 29 technique illustrations load, including floor press offline', async ({ page, context }) => {
  await page.goto('./')
  await page.getByRole('button', { name: 'Начать тренировку' }).click()
  const buttons = page.locator('button.technique-link')
  await expect(buttons).toHaveCount(29)
  for (let i = 0; i < 29; i++) {
    await buttons.nth(i).click()
    const image = page.locator('.media img')
    await expect(image).toBeVisible()
    await expect.poll(() => image.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true)
    await page.keyboard.press('Escape')
  }
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await page.reload()
  await context.setOffline(true)
  await page.getByRole('button', { name: 'Продолжить тренировку' }).click()
  const floorPress = page.locator('.exercise-card').filter({ hasText: 'Жим гантелей лёжа на полу' })
  await floorPress.locator('button.technique-link').click()
  await expect(page.getByRole('img', { name: 'Техника: Жим гантелей лёжа на полу' })).toBeVisible()
  await expect.poll(() => page.locator('.media img').evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true)
  await context.setOffline(false)
})
